### ISSUE TITLE
Couldn't open "3ds/3ds-remote-linux/3ds-remote-linux.ini"

### ISSUE THREAD

**Issue by undercooks** [wilm0x42/3ds-remote-linux#1]
config file is in the specified folder on the 3DS SD card, but 3DS cannot open the ini. It has a fatal error trying to create a file there I am using old 3DS with homebrew launcher.

**Comment by wilm0x42** [comment]
Uhhhh this is a _very_ old repo, but um.
In order to help ya, I'll need more info than that-- a specific error code would be good start.
A screenshot could help too.
(Also this is _not_ a good quality piece of software, I do not reccommend :P)

**Comment by undercooks** [comment]
Thanks for responding! The program is very impressive, there's just an error is on the client side, I've attached a picture of the error message from the 3DS.
![error_code](https://user-images.githubusercontent.com/78812071/108003311-62632200-6fc0-11eb-94cf-a115856a08d9.jpg)
Error reads Couldn't open "3ds/3ds-remote-linux/3ds-remote-linux.ini". Creating new. . .FATAL : Could not create "3ds/3ds-remote-linux/3ds-remote-linux.ini"
Error: iniFp is NULL
Error (2): Error: "serveraddr" MUST be within the .ini file!
Since the error seems to be with retrieving the config file I might be able to just edit the ini.c file so it contains the IP information since I'll be using the 3ds with a computer with a fixed IP.

**Comment by undercooks** [comment]
I removed the ini.h header from the net.c and main.c files and replaced the ini calls in those files with the port and address info. It compiled no problems and it runs fine now! Probably the file system organization got changed in some update, which is why the program couldn't find the config file, but the rest of the program is great. Thanks for your work on this program it's super helpful :)
